### ISSUE TITLE
Allow Admin to import employers from CSV

### ISSUE THREAD

**Issue by finleye** [SCCapstone/CareerCenterApp#10]
This should be a link in the admin navigation

**Comment by andrewkazura** [comment]
where do you want the link to be sourced to?

**Comment by finleye** [comment]
I've fixed this and it's currently in production. Can someone test it out and make sure that it's working? After you upload you should delete the newly added ones. You'll have to do this @andrewkazura 

From the app directory on your machine run `heroku run rails c` to open the console on the production machine. Then run `Employer.where("created_at > ?", Time.now-60*60).delete_all. That will batch delete all events added in the past hour. If you can't access the console after import, let me know and I'll batch delete them. But we need to make sure you have access to the production server.

**Comment by andrewkazura** [comment]
It uploads all the companies and I was able to delete all events as well
