### ISSUE TITLE
Navbar spacing broken

### ISSUE THREAD

**Issue by finleye** [SCCapstone/CareerCenterApp#11]
![screenshot 2014-02-04 22 40 38](https://f.cloud.github.com/assets/2751136/2084134/679eae7a-8e17-11e3-802f-8c6c4c986c2d.png)
The white space above the navbar needs to be fixed. It's probably margin-top on that object. There's also an issue with the list items being to close to the top of the navbar. I know this has been your issue @andrewkazura , so I'll assign it to you.

**Comment by andrewkazura** [comment]
just submitted a solution check to make sure that it works when you get the chance
