### ISSUE TITLE
users are duplicating in the database

### ISSUE THREAD

**Issue by finleye** [SCCapstone/CareerCenterApp#15]
We need to verify uniqueness of email addresses when users are added. There are multiple instances of accounts.

**Comment by ballardaf** [comment]
I checked after we got off of skype and I don't see the duplicates in the database. 2 are from my two different gmail accounts and the 3rd, hero, was made at the start of the project for testing purposes. I'm not sure about Andrew K's or yours. 

Edit: Ah, on the live site is the bug. Hmm, looking into
Edit2: And I broke the live site by mistake by deleting my own user ids from the database

**Comment by finleye** [comment]
@ballardaf said he looked into this and it was a legacy problem that had been resolved in the newest version. Closing.
