### ISSUE TITLE
employers listing is scoped based on presence of current_conference being set

### ISSUE THREAD

**Issue by finleye** [SCCapstone/CareerCenterApp#28]
if the session token for the current conference has been set, listings should be scoped to only include the employers for that conference.

**Comment by finleye** [comment]
@ballardaf will be working on setting the session token for the current conference. I set up an application helper method called `current_con` that will set the current conference based on the session token. You can see that it checks the session token with `session[:current_con]` it expects this value to be an integer, the foreign key for the conference model. Let me know if you have questions about how you should be setting that value.

**Comment by ballardaf** [comment]
This is pretty much part of issue #26 which should be resolved. Just needs to be reviewed and merged.

**Comment by ballardaf** [comment]
Quality assurance looks good and seems to be functioning correctly
