### ISSUE TITLE
USC logo in the nav bar needs to link to root_path

### ISSUE THREAD

**Issue by finleye** [SCCapstone/CareerCenterApp#34]
clicking the logo should take you back to the home page

**Comment by ballardaf** [comment]
Also, Conferences link needs to link to /select_con. It's better to do this with the link_to method

 get "conferences/select_con" => "conferences#select_con" - located in routes.rb

**Comment by ballardaf** [comment]
Fixed by Andrew K. and pushed to production by Corey
