### ISSUE TITLE
Create Testing Feedback wiki page

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CareerCenterApp#37]
By now you should have shown the beta website to Helen and received some feedback from her.

In the Testing Feedback wiki page you will put all the comments you've gotten from Helen, and anyone else you've gotten to test your app. Just a bunch of bullet points.

The goal is to figure out if there are any common pain points across the users, and then fix those UI issues.

**Comment by ballardaf** [comment]
The page has been created and were filling it with information.
