### ISSUE TITLE
Let anyone create their own Career Fair

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CareerCenterApp#5]
Your webapp will start by letting a user (say, Helen) create a Career Fair (say SET Spring 2014). Then she will populate it with the needed information.

**Comment by finleye** [comment]
@josemvidal only admin's should be allowed to do this right? not just anyone.

**Comment by josemvidal** [comment]
Well, I see this a a webapp where anyone can create their own Fair, which they then own.

The same way I can create a google doc and then let others edit it, and let the world view it.

**Comment by ballardaf** [comment]
So who's going to pay for the extra space in the database for several schools to use this app?

**Comment by josemvidal** [comment]
If you decide to give this a shot after class is over, and I hope you do, your revenue options are the usual: either charge your users or use advertising.

For this app it seems clear that the organizer of the fair (the school) is willing to pay money. You already have one such person willing to pay, with their time. The bigger the fair, the more attendees, the more they would be willing to pay. So, I would charge people to create fairs.

Of course, you will have to give it away for free until you get enough word-of-mouth.

Another thought: if you add some data-entry to your pitch, like offering to enter all the data for the fair (companies and maps) for them, you will get even more sales. Remember the person making the decision would be buying this with someone else's money. So they are thinking, "I could do all this by hand, printing maps, sending individual emails, etc. or I could get my employer to pay them $1000, send 1 email with all the info, and every attendee gets custom mobile app". If it takes you 10 hours of cut-n-paste, that's $100/hour for cut-n-paste work. Not bad. Hire me to do it!

**Comment by ballardaf** [comment]
This feature was implemented when Corey set up the application models; therefore, any admin user can create their own fair.
