### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by ballardaf** [SCCapstone/CareerCenterApp#55]
Video: if not logged in, show video of how to use the app. Otherwise, act as normally. Screen cast would make this ideal. Include @finleye

**Comment by andrewkazura** [comment]
need to make sure to explain that you can login with a gmail or any email registered with google which can include your @email.sc.edu

**Comment by andrewkazura** [comment]
here it is. @finleye This is the student how to, we aren't going to do an admin because of the errors we are fixing right now and we are going to show them anyway

https://www.youtube.com/watch?v=E44FhfeLEUU

**Comment by ballardaf** [comment]
The video is up on the live site and is functioning properly.
