### ISSUE TITLE
Quality Assurance

### ISSUE THREAD

**Issue by ballardaf** [SCCapstone/CareerCenterApp#56]
Finishing quality assurance tonight

**Comment by ballardaf** [comment]
Started doing manual QA test on the entire application. I have a readme file with some updates for nonlogged in users and the student roles. I'll be doing an in-depth admin check soon with reports on my findings. After these fixs, we'll have our clients take another look at the application for one final feedback session. @finleye @andrewkazura  @jayposton

**Comment by andrewkazura** [comment]
everybody should be done

**Comment by andrewkazura** [comment]
@finleye you need to add your 3 to the roomscheduling page
