### ISSUE TITLE
Upload and show Company logos

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/CareerCenterApp#6]

**Comment by finleye** [comment]
almost working
![snorlax](http://pldh.net/media/dreamworld/143.png)

**Comment by finleye** [comment]
merged and working. someone QA this for me. @SCCapstone/careercenterapp

**Comment by andrewkazura** [comment]
where are the logos supposed to be? I tried looking for them but couldn't find anything @finleye

**Comment by andrewkazura** [comment]
nvm works

**Comment by ballardaf** [comment]
working and closing
