### ISSUE TITLE
When you add a company to your favorites, the name doesn't show up under view profile

### ISSUE THREAD

**Issue by OptimusMaximus** [SCCapstone/CareerCenterApp#61]
I chose PepsiCo as a favorite.  It comes up as "528" instead of the name under view my profile.

**Comment by andrewkazura** [comment]
in view profile the only information that should be shown is name, role, email. they should not be able to click edit, back, see favorites, source, token.

hopefully it will help stop the replicating usernames

**Comment by ballardaf** [comment]
Yeah, they shouldn't be able to change any of this information. If they do, they essentially create a new user in the database because they change the tuple essential. Google handles all login information. If they wanna change it they can go to their gmail and change it there

**Comment by finleye** [comment]
This was marked QA but i don't think it's been done

**Comment by ballardaf** [comment]
Just needs to be merged and QA'ed

**Comment by finleye** [comment]
I see no merge request.

**Comment by andrewkazura** [comment]
@finleye to fix it i just hid all of that information. it has already been merged in with my last request #73

**Comment by finleye** [comment]
my mistake. I rebased dev and lost the commit history.
