### ISSUE TITLE
When I click on users from the drop down menu under my name, it doesn't do anything

### ISSUE THREAD

**Issue by OptimusMaximus** [SCCapstone/CareerCenterApp#63]
Is this feature only for an admin? Sometimes it will tell me that I'm not authorized to do that.  Other times it won't give me the message.  I've tried to recreate the steps I've taken to not get the message, but I'm not sure how I did it.

**Comment by andrewkazura** [comment]
it is a feature for the admin but I am just going to get rid of it there because there is another link in the admin tools section for it.

**Comment by finleye** [comment]
This has been resolved.
