### ISSUE TITLE
When I click back button under view profile, it always takes me to Employers page

### ISSUE THREAD

**Issue by OptimusMaximus** [SCCapstone/CareerCenterApp#64]
I was on the Map page, clicked drop down menu for view profile, hit back button and it takes me to Employers page instead of back to Map page.  It does the same thing regardless of what page you were originally on.

**Comment by andrewkazura** [comment]
@OptimusMaximus We are having trouble recreating your error. Did you load your profile page first before clicking back or did you just open up the dropdown?

**Comment by OptimusMaximus** [comment]
Yeah I had my profile loaded already.  I click on view profile and it brings up name, role, etc.  I click the back button on that view profile page and it takes me back but to the original page I was on.  So I was on maps page and I clicked on my name, then view profile, then back button, it wouldn't take me back to map page but instead it would take me to the Employers page.

**Comment by ballardaf** [comment]
Yeah, I tried and I can't seem to reproduce this error. We'll continue to investigate though

**Comment by andrewkazura** [comment]
@ballardaf when you click the button that says "back" at the bottom of the page not back for the browser it sends you to the all users page if you are an admin but otherwise it would send you to the employers since you aren't allowed on the all users page

**Comment by andrewkazura** [comment]
I got rid of that button in the users view since it really is for admin use

**Comment by finleye** [comment]
looks good
