### ISSUE TITLE
Under employers, at the very bottom of the page, there is an invalid employer

### ISSUE THREAD

**Issue by OptimusMaximus** [SCCapstone/CareerCenterApp#65]
This is what is located at the bottom of the page for an employer. *Southeast Refers to: TN, GA, LA, AL, FL, SC, AR, KY, MS

**Comment by Bensnorman** [comment]
I think this clarification statement would be better at the very top of the employer list. And not listed as a link.

**Comment by finleye** [comment]
this has been done.
