### ISSUE TITLE
*Feature*When you click "More Info" in an employer, it would be cool to have a pop up or drop down bar

### ISSUE THREAD

**Issue by Bensnorman** [SCCapstone/CareerCenterApp#67]
When you click "More Info" in an employer, it would be cool to have a pop up or drop down bar with a couple of lines about the company. Because clicking the name of the company and the "More Info" button take you to the same place. It would be awesome to click more info, stay on the same page, and read a couple of lines about the company.

**Comment by andrewkazura** [comment]
Since there is no other way to go to the employers page other then clicking on the company's name and we aren't stating that you can do this it would make it almost impossible for users to find the employers page.
