### ISSUE TITLE
Error when trying to view "Favorite Employers"

### ISSUE THREAD

**Issue by Bensnorman** [SCCapstone/CareerCenterApp#68]
![screen shot 2014-04-11 at 12 13 35 pm](https://cloud.githubusercontent.com/assets/5401596/2682002/6408af76-c194-11e3-9f1d-e4ab67e3e296.png)

**Comment by andrewkazura** [comment]
If an employer is deleted delete them from all users' favorite employers list

**Comment by ballardaf** [comment]
Also, deleting the removed employer(s) from everyone' favorite list at the time of the deletion should also fix the duplicate users in the database issue.

**Comment by finleye** [comment]
I'm not really sure how to tackle this problem. I'll have to look into it more.

**Comment by ballardaf** [comment]
Solved!
