### ISSUE TITLE
Edit Employers Page

### ISSUE THREAD

**Issue by andrewkazura** [SCCapstone/CareerCenterApp#69]
- [x] 1. Error message for edit employers when they do not have all of the information inputted needs to be clarified. Required fields should be indicated somehow 
- [x] 2. hide created,updated,last edit.
- [x] 3. table isn't being brought over to the edit employers when it is added by the csv file.
- [x] 4. image file name is not being transferred when you press the edit button for the employers which is a required field. 
- [x] 5. after a employer is edited and saved it is pushed to the bottom of the page

**Comment by finleye** [comment]
point 3, the table in the form is still the ID not the string field.

sort the index alphabetically.

**Comment by finleye** [comment]
the problem caused by the first point was to do with the image upload. It's been fixed.

**Comment by finleye** [comment]
point 5 was caused by the index being sorted by the `updated_at` field. It is now sorted by name.

**Comment by ballardaf** [comment]
Yeah, everything seems to be working correctly here.
