### ISSUE TITLE
Can't log in with @email.sc.edu

### ISSUE THREAD

**Issue by skylar-smith** [SCCapstone/CareerCenterApp#71]
A lot of students only use their @email.sc.edu accounts. It would probably be a good idea to allow them to log in with those accounts. If I didn't have a gmail account and had to get one to use this app then I just wouldn't use it. Users are lazy.

Also if you are signed into your gmail account it auto signs you in with that account. So if I want to let someone else use this app from my computer I have to log out your app and also log out of gmail. Again lazy user problem.

**Comment by finleye** [comment]
@skysmith112 we're using OpenID for login. We thought it would be easier to allow someone to sign in with an existing account than have to make a new account on our system. @email.sc.edu doesn't have an API we can use for login that I know of.

**Comment by andrewkazura** [comment]
you can register your @email.sc.edu with google so that it will work with the google api. i know it doesn't fix the fact that students are lazy but you can use your @email.sc.edu.

**Comment by andrewkazura** [comment]
I am going to close this since it shall be addressed in the video on how to navigate through the site.
