### ISSUE TITLE
Change domain

### ISSUE THREAD

**Issue by finleye** [SCCapstone/CareerCenterApp#78]
We need to change the domain. Something for sc.edu @andrewkazura suggested sc.edu/careercenter or something like that, but I've realized that's not going to work. It needs to be <somename>.sc.edu because the path needs to be unaltered. I know how to set the application up to accept a different domain, but that's about it. Who else can tackle getting this taken care of? @SCCapstone/careercenterapp

**Comment by andrewkazura** [comment]
i will look into it. just a preliminary look but unless we buy a new url we can't have a new root. 

But if we change the project name in heroku then that will change the current url from stormy-messa-3110.herokuapp.com to newname.herokuapp.com. If we do that I think that will be acceptable and then we can allow them to have a page on sc.edu that will tell students about our app and have a link to it.

In our discussion today we talked with Helen and Matt and that was a possibility. What do you guys think of that plan? @SCCapstone/careercenterapp

**Comment by finleye** [comment]
Oh I see. That might be doable. —
Corey Finley
Developer
803.767.7339

**Comment by andrewkazura** [comment]
If we are going with that route it is just one line from the command line and it should update everything. We might need to change the google login api code like you said corey 

https://devcenter.heroku.com/articles/renaming-apps

here is the command itself all we need now will be the name that they want the link to be:
$ heroku apps:rename newname

**Comment by finleye** [comment]
I’ve renamed the app to careercenterapp I’m trying to figure out why it’s crashing.
-- 
Corey Finley
Sent with Airmail

On April 21, 2014 at 8:54:16 PM, andrewkazura (notifications@github.com) wrote:

If we are going with that route it is just one line from the command line and it should update everything. We might need to change the google login api code like you said corey

https://devcenter.heroku.com/articles/renaming-apps

here is the command itself all we need now will be the name that they want the link to be:
$ heroku apps:rename newname

**Comment by finleye** [comment]
done. The app is now at https://careercenterapp.herokuapp.com
