### ISSUE TITLE
CSV File - Import All Fields

### ISSUE THREAD

**Issue by ballardaf** [SCCapstone/CareerCenterApp#82]
Import all fields from employers into the CSV file except logos obviously. Some might be blank so account for that. This makes it so they can control everything from just the CSV file except logos.

**Comment by finleye** [comment]
can you send me the CSV's with more fields?

**Comment by finleye** [comment]
previous CSV upload design,
column 0: table number
column 1: name
column 2: majors
column 3-10: positions and locations

added support:
column 11: description
column 12: website
column 13: location
column 14: tips
column 15: contact email

**Comment by ballardaf** [comment]
Works, closing this issue!
