### ISSUE TITLE
Menu Bar - Confenerce and Fair Links Update

### ISSUE THREAD

**Issue by ballardaf** [SCCapstone/CareerCenterApp#91]
- [x] 1. Conference and Curre_Fair lead to the same place. Remove conference and add "Fair:"in front of fair_name
- [x] 2. On all conferences page, change conferences to All Fairs or All Job Fairs

**Comment by jayposton** [comment]
Conferences changed to All Job Fairs

**Comment by ballardaf** [comment]
Please don't commit or push changes to development - you should be making changes on a difference branch and following up with Corey to merge them into development. Thanks!
